// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Process credit card payment
	// (POST /payments/checkout)
	ProcessPayment(w http.ResponseWriter, r *http.Request)
	// Get product by ID
	// (GET /products/{productId})
	GetProduct(w http.ResponseWriter, r *http.Request, productId int32)
	// Add product details
	// (POST /products/{productId}/details)
	AddProductDetails(w http.ResponseWriter, r *http.Request, productId int32)
	// Create a new shopping cart
	// (POST /shopping-carts)
	CreateShoppingCart(w http.ResponseWriter, r *http.Request)
	// Checkout shopping cart
	// (POST /shopping-carts/{shoppingCartId}/checkout)
	CheckoutCart(w http.ResponseWriter, r *http.Request, shoppingCartId int32)
	// Add items to shopping cart
	// (POST /shopping-carts/{shoppingCartId}/items)
	AddItemsToCart(w http.ResponseWriter, r *http.Request, shoppingCartId int32)
	// Reserve product inventory
	// (POST /warehouse/reserve)
	ReserveInventory(w http.ResponseWriter, r *http.Request)
	// Ship product
	// (POST /warehouse/ship)
	ShipProduct(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Process credit card payment
// (POST /payments/checkout)
func (_ Unimplemented) ProcessPayment(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get product by ID
// (GET /products/{productId})
func (_ Unimplemented) GetProduct(w http.ResponseWriter, r *http.Request, productId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add product details
// (POST /products/{productId}/details)
func (_ Unimplemented) AddProductDetails(w http.ResponseWriter, r *http.Request, productId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new shopping cart
// (POST /shopping-carts)
func (_ Unimplemented) CreateShoppingCart(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Checkout shopping cart
// (POST /shopping-carts/{shoppingCartId}/checkout)
func (_ Unimplemented) CheckoutCart(w http.ResponseWriter, r *http.Request, shoppingCartId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add items to shopping cart
// (POST /shopping-carts/{shoppingCartId}/items)
func (_ Unimplemented) AddItemsToCart(w http.ResponseWriter, r *http.Request, shoppingCartId int32) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reserve product inventory
// (POST /warehouse/reserve)
func (_ Unimplemented) ReserveInventory(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Ship product
// (POST /warehouse/ship)
func (_ Unimplemented) ShipProduct(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ProcessPayment operation middleware
func (siw *ServerInterfaceWrapper) ProcessPayment(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ProcessPayment(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProduct operation middleware
func (siw *ServerInterfaceWrapper) GetProduct(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId int32

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProduct(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddProductDetails operation middleware
func (siw *ServerInterfaceWrapper) AddProductDetails(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "productId" -------------
	var productId int32

	err = runtime.BindStyledParameterWithOptions("simple", "productId", chi.URLParam(r, "productId"), &productId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "productId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddProductDetails(w, r, productId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateShoppingCart operation middleware
func (siw *ServerInterfaceWrapper) CreateShoppingCart(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateShoppingCart(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CheckoutCart operation middleware
func (siw *ServerInterfaceWrapper) CheckoutCart(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shoppingCartId" -------------
	var shoppingCartId int32

	err = runtime.BindStyledParameterWithOptions("simple", "shoppingCartId", chi.URLParam(r, "shoppingCartId"), &shoppingCartId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shoppingCartId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckoutCart(w, r, shoppingCartId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AddItemsToCart operation middleware
func (siw *ServerInterfaceWrapper) AddItemsToCart(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "shoppingCartId" -------------
	var shoppingCartId int32

	err = runtime.BindStyledParameterWithOptions("simple", "shoppingCartId", chi.URLParam(r, "shoppingCartId"), &shoppingCartId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "shoppingCartId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AddItemsToCart(w, r, shoppingCartId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReserveInventory operation middleware
func (siw *ServerInterfaceWrapper) ReserveInventory(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReserveInventory(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ShipProduct operation middleware
func (siw *ServerInterfaceWrapper) ShipProduct(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ShipProduct(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/payments/checkout", wrapper.ProcessPayment)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/products/{productId}", wrapper.GetProduct)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/products/{productId}/details", wrapper.AddProductDetails)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/shopping-carts", wrapper.CreateShoppingCart)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/shopping-carts/{shoppingCartId}/checkout", wrapper.CheckoutCart)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/shopping-carts/{shoppingCartId}/items", wrapper.AddItemsToCart)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/warehouse/reserve", wrapper.ReserveInventory)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/warehouse/ship", wrapper.ShipProduct)
	})

	return r
}
