// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	// Details Additional error details
	Details *string `json:"details,omitempty"`

	// Error Error code
	Error string `json:"error"`

	// Message Human-readable error message
	Message string `json:"message"`
}

// Product defines model for Product.
type Product struct {
	// CategoryId Product category identifier
	CategoryId int32 `json:"category_id"`

	// Manufacturer Product manufacturer name
	Manufacturer string `json:"manufacturer"`

	// ProductId Unique identifier for the product
	ProductId int32 `json:"product_id"`

	// Sku Stock Keeping Unit - unique product code
	Sku string `json:"sku"`

	// SomeOtherId Additional identifier for product
	SomeOtherId int32 `json:"some_other_id"`

	// Weight Product weight in grams
	Weight int32 `json:"weight"`
}

// ProcessPaymentJSONBody defines parameters for ProcessPayment.
type ProcessPaymentJSONBody struct {
	// CreditCardNumber Credit card number (13-19 digits)
	CreditCardNumber string `json:"credit_card_number"`

	// ShoppingCartId Unique identifier for the shopping cart
	ShoppingCartId int32 `json:"shopping_cart_id"`
}

// CreateShoppingCartJSONBody defines parameters for CreateShoppingCart.
type CreateShoppingCartJSONBody struct {
	// CustomerId Unique identifier for the customer
	CustomerId int32 `json:"customer_id"`
}

// AddItemsToCartJSONBody defines parameters for AddItemsToCart.
type AddItemsToCartJSONBody struct {
	// ProductId Unique identifier for the product
	ProductId int32 `json:"product_id"`

	// Quantity Number of items to add
	Quantity int32 `json:"quantity"`
}

// ReserveInventoryJSONBody defines parameters for ReserveInventory.
type ReserveInventoryJSONBody struct {
	// ProductId Unique identifier for the product
	ProductId int32 `json:"product_id"`

	// Quantity Quantity to reserve
	Quantity int32 `json:"quantity"`
}

// ShipProductJSONBody defines parameters for ShipProduct.
type ShipProductJSONBody struct {
	// ProductId Unique identifier for the product
	ProductId int32 `json:"product_id"`

	// Quantity Quantity to ship
	Quantity int32 `json:"quantity"`
}

// ProcessPaymentJSONRequestBody defines body for ProcessPayment for application/json ContentType.
type ProcessPaymentJSONRequestBody ProcessPaymentJSONBody

// AddProductDetailsJSONRequestBody defines body for AddProductDetails for application/json ContentType.
type AddProductDetailsJSONRequestBody = Product

// CreateShoppingCartJSONRequestBody defines body for CreateShoppingCart for application/json ContentType.
type CreateShoppingCartJSONRequestBody CreateShoppingCartJSONBody

// AddItemsToCartJSONRequestBody defines body for AddItemsToCart for application/json ContentType.
type AddItemsToCartJSONRequestBody AddItemsToCartJSONBody

// ReserveInventoryJSONRequestBody defines body for ReserveInventory for application/json ContentType.
type ReserveInventoryJSONRequestBody ReserveInventoryJSONBody

// ShipProductJSONRequestBody defines body for ShipProduct for application/json ContentType.
type ShipProductJSONRequestBody ShipProductJSONBody
